### ISSUE TITLE
can I propose you display pin 1 as a square pad in the top-down view? I think that's pretty typical on PCBs

### ISSUE THREAD

**Issue by azaslavskis** [azaslavskis/PinoutGenerator#3]
app: web app
problem: can I propose you display pin 1 as a square pad in the top-down view? I think that's pretty typical on PCBs

**Comment by azaslavskis** [comment]
![image](https://user-images.githubusercontent.com/20460747/230481903-0d07ad02-54ec-4342-bc25-c9d0f135ab50.png)
is what been meant?

**Comment by azaslavskis** [comment]
![image](https://user-images.githubusercontent.com/20460747/230482770-ee9d33d4-3387-4bfa-a1ac-3f0c44714e88.png)

more neat way of same thing.

**Comment by graymalkin** [comment]
Aye this is what I was imagining. Looks great!

**Comment by azaslavskis** [comment]
@graymalkin time to close this issue :)
